### ISSUE TITLE
Hook error with Taskwarrior 2.4.1

### ISSUE THREAD

**Issue by regagain** [JensErat/task-relative-recur#6]
Hi!

Since I upgraded to Taskwarrior 2.4.1, I keep getting the following error when completing a task that has relativeRecur\* attributes:

`Hook Error: Expected 1 JSON task(s), found 2`

Anybody else seeing this?

**Comment by JensErat** [comment]
I fear that the hook broke because 2.4.1 disallows creation of new tasks. I will look into that in the weekend, and if everything else breaks, I will workaround that limitation by adding the task through directly calling `task add` somehow. Not a beautiful workaround, but should get the hook running again.

**Comment by JensErat** [comment]
I've got a workaround running (mostly) that calls `task import` after taskwarrior completed, but there's still an issue with some open file descriptors that have to be resolved. Some change to taskwarrior (where I do not fully grasp the consequences) doing so is currently discussed. Expect some resolution within the next few days.

**Comment by JensErat** [comment]
The taskwarrior issue was confirmed, and will be resolved soon. I will push a fixed hook as soon as there is a patch on the 2.4.2 branch. Seems the 2.4.1 release will never be supported by the hook.

**Comment by regagain** [comment]
Thanks! Really looking forward to this.
Meanwhile.. I'm staying on 2.4.0 :)

**Comment by JensErat** [comment]
The issue is already fixed, and I pushed the workaround for creating tasks. The hook now requires a Task Warrior 2.4.2 build from 2015-02-22 (not older than around 30 minutes from the time posting this comment).

The message "Created follow-up task" currently does not appear (unless setting `rc.debug.hooks=2`), this is another, know Task Warrior bug to be resolved. The task _does_ get created, though.
